//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int id { get; set; }
        public Nullable<int> idcategoria { get; set; }
        public string nome { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
